services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb:10.5 # On utilise MariaDB pour la compatibilité avec ton Mac
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'imovies'
    volumes:
      - ./imovies_users.dump.txt:/docker-entrypoint-initdb.d/init.sql